"""Add token_cost_per_bid to Auction model

Revision ID: 0aa7d678a07a
Revises: d9410fccc4e2
Create Date: 2025-04-24 18:52:51.032452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa7d678a07a'
down_revision = 'd9410fccc4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_cost_per_bid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_column('token_cost_per_bid')

    # ### end Alembic commands ###
