"""Update Product model

Revision ID: 0c2cdab37d50
Revises: 3b3d0bb6c179
Create Date: 2025-04-06 18:31:55.164618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2cdab37d50'
down_revision = '3b3d0bb6c179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('product_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('starting_price')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()))
        batch_op.create_unique_constraint('uq_products_name', ['name'])  # Explicit name for the unique constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_name', type_='unique')  # Explicit name for the unique constraint
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('starting_price', sa.Float(), nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_description')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###