"""Add amount column to bids table

Revision ID: 6ab1286f2f11
Revises: 0c2cdab37d50
Create Date: 2025-04-06 19:26:17.791901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab1286f2f11'
down_revision = '0c2cdab37d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('bid_amount')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('bid_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
